spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: "mongodb+srv://nishantrathore2002:rootuser@cluster0.0l1yo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: "UserService"

server:
  port: 9001


cloudinary:
  cloud_name: "dctoqfkw0"
  api_key: "951526354525734"
  api_secret: "0YOP7Q-AasOxPHuE7O5w-A5Hwhw"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
