spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      global-cors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "http://localhost:5173"
                allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                allowedHeaders:
                - "*"
                allowCredentials: true

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 9003