spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/messages/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      global-cors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "http://localhost:5173"
                allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                allowedHeaders:
                - "*"
                allowCredentials: true


eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 9003
